<a href="https://colab.research.google.com/github/HarshadShah3/Python-Programs/blob/main/Practical7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Roll no. : I056

Program: B.Tech CS-AI

Semester: 2

Name : Harshad Shah

Batch: I2

#Task 1
##Write a Python program to reverse an array without using an in-built function.

In [2]:
from array import*

In [ ]:
a1= array('i',[])
for i in range(0,5):
  a1.append(int(input('Enter number {}. : '.format(i+1))))

print('Original Array: ', a1)

a2 = array('i', [])
for i in range(len(a1)-1, -1,-1):
  a2.append(a1[i])

print('Reversed Array: ', a2)

Enter number 1. : 50
Enter number 2. : 40
Enter number 3. : 30
Enter number 4. : 20
Enter number 5. : 10
Original Array:  array('i', [50, 40, 30, 20, 10])
Reversed Array:  array('i', [10, 20, 30, 40, 50])


#Task 2
##Write a Python program to find the frequency of a user given number in an array. (without using an in-built function)

In [ ]:
a = array('i',[])
for i in range(0,5):
  a.append(int(input('Enter element {} of array. : '.format(i+1))))
print()
print('Array is: ',a)
n = int(input('Enter the number to find its frequency: '))
c=0  
for i in a:
  if n==i:
    c+=1
  else:
    continue

print('Frequency of {} is {}.'.format(n,c))

Enter element 1 of array. : 12
Enter element 2 of array. : 24
Enter element 3 of array. : 50
Enter element 4 of array. : 24
Enter element 5 of array. : 81

Array is:  array('i', [12, 24, 50, 24, 81])
Enter the number to find its frequency: 24
Frequency of 24 is 2.


#Task 3: 
##Write a Python program to place all negative numbers in the array at the end of the array and positive numbers in the beginning.


In [ ]:
a = array('i', [1,-2,4,-6,-4,9,6,-7])
print('Mixed Array: ',a)
print()
pos = array('i', [])
neg = array('i', [])

for i in a:
  if i>0:
    pos.append(i)
  else:
    neg.append(i)

print('Positive number Array: ', pos)
print('Negative number Array: ', neg)

pos.extend(neg)
print()
print('Final Array: ', pos)

Mixed Array:  array('i', [1, -2, 4, -6, -4, 9, 6, -7])

Positive number Array:  array('i', [1, 4, 9, 6])
Negative number Array:  array('i', [-2, -6, -4, -7])

Final Array:  array('i', [1, 4, 9, 6, -2, -6, -4, -7])


#Task 4
##Write a Python program to sort an array in wave form.


In [3]:
a = array('i', [2,4,6,8,10,20])
print('Original Array: ',a)

x = 0
y = 1
t = 0

for i in range (0,6):
    for j in range(i + 1, 6):
        if(a[i] > a[j]):
            t = a[i]
            a[i] = a[j]
            a[j] = t

for k in range(0,3):
  t = a[x]
  a[x] = a[y]
  a[y] = t
  x+=2
  y+=2

print('Wave Form Array: ',a)

Original Array:  array('i', [2, 4, 6, 8, 10, 20])
Wave Form Array:  array('i', [4, 2, 8, 6, 20, 10])


#Task 5
##Write a Python program to print a given matrix in spiral form.



In [11]:
def spiral(a, row, col):
  sr = 0  #row index
  sc = 0  #coumn index
 
  while (sr < row and sc < col):
      for i in range(sc, col):
          print(a[sr][i], end=" ")
      sr += 1  #sr=1


      for i in range(sr, row):   
           print(a[i][col - 1], end=" ")
      col-= 1   #col =  2
 

      if (sr < row):
        for i in range(col - 1, (sc - 1), -1):
          print(a[row - 1][i], end=" ")
        row -= 1
 
      if (sc < col):
        for i in range(row - 1, sr - 1, -1):
          print(a[i][sc], end=" ")
        sc += 1

a = [[1,2,3,4,5],
     [6,7,8,9,10],
     [11,12,13,14,15]]

print('Original Matrix:')
print(a)
print()
print('After Spiral: ')

row = 3
col = 5
spiral(a, row, col)

Original Matrix:
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]

After Spiral: 
1 2 3 4 5 10 15 14 13 12 11 6 7 8 9 

#Task 6.1
##Write a Python program to print ‘k’ smallest element in an unsorted array.

In [10]:
a = array('i',[])
for i in range(0,5):
  a.append(int(input('Enter element {} of array. : '.format(i+1))))
print('Array: ',a)

n= int(input('Enter which smallest value: '))

for i in range (0,5):
    for j in range(i + 1, 5):
        if(a[i] > a[j]):
            t = a[i]
            a[i] = a[j]
            a[j] = t
print('Sorted array: ',a)
print('The "{}" smallest element is {}.'.format(n,a[n-1]))


Enter element 1 of array. : 3
Enter element 2 of array. : 0
Enter element 3 of array. : 1
Enter element 4 of array. : 7
Enter element 5 of array. : 4
Array:  array('i', [3, 0, 1, 7, 4])
Enter which smallest value: 4
Sorted array:  array('i', [0, 1, 3, 4, 7])
The "4" smallest element is 4.


#Task 6.2
##Write a Python program to print ‘k’ largest element in an unsorted array.

In [9]:
7a = array('i',[])
for i in range(0,5):
  a.append(int(input('Enter element {} of array. : '.format(i+1))))
print('Array: ',a)

n= int(input('Enter which largest value: '))

for i in range (0,5):
    for j in range(i + 1, 5):
        if(a[i] < a[j]):
            t = a[i]
            a[i] = a[j]
            a[j] = t
print('Sorted array: ',a)
print('The "{}" largest element is {}.'.format(n,a[n-1]))

Enter element 1 of array. : 9
Enter element 2 of array. : 8
Enter element 3 of array. : 6
Enter element 4 of array. : 2
Enter element 5 of array. : 7
Array:  array('i', [9, 8, 6, 2, 7])
Enter which largest value: 3
Sorted array:  array('i', [9, 8, 7, 6, 2])
The "3" largest element is 7.


#Task 7
##Write a Python Program to add two 3x3 Matrices using Nested Loop.


In [8]:
a1 = [[1,2,3],[4,5,6], [7,8,9]]
a2 = [[3,6,9],[2,5,8], [1,4,7]]
add = [[0,0,0],[0,0,0], [0,0,0]]

for i in range(0, 3):
  for j in range(0, 3):
    add[i][j] = a1[i][j] + a2[i][j]
  
print('Addition of two matrices is: ')
for a in add:
    print(a)

Addition of two matrices is: 
[4, 8, 12]
[6, 10, 14]
[8, 12, 16]


#Task 8:
##Write a Python Program to multiply two Matrices using Nested Loop.

In [7]:
a1 = np.array([[1,2,3],[4,5,6], [7,8,9]])
print('Matrix 1: ')
print(a1)

print()

a2 = np.array([[3,6,9],[2,5,8], [1,4,7]])
print('Matrix 2: ')
print(a2)

mul = np.array([[0,0,0],[0,0,0], [0,0,0]])

for i in range(0, 3):
  for j in range(0, 3):
    for k in range(0,3):
      mul[i][j]+=(a1[i][k] * a2[k][j])

print()  
print('Multiplication of two matrices is: ')
print(mul)

Matrix 1: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 2: 
[[3 6 9]
 [2 5 8]
 [1 4 7]]

Multiplication of two matrices is: 
[[ 10  28  46]
 [ 28  73 118]
 [ 46 118 190]]


#Task 9
##Write a Python Program to Calculate the sum of all columns in a 2D NumPy array



In [5]:
import numpy as np

In [ ]:
a= np.array([[1,2,3],[1,1,1],[1,1,1]])
print('Array is: ')
print(a)
colsum =[]
for i in range(0,3):
  sum=0
  for j in range(0,3):
    sum = a[j][i]+sum
  colsum.append(sum)
print('Column wise Sum: ', colsum) 

Array is: 
[[1 2 3]
 [1 1 1]
 [1 1 1]]
Column wise Sum:  [3, 4, 5]


#Task 10:
##Write a Python Program to find Range and Coefficient of range of Array.


In [ ]:
a = np.array([10, 20, 30, 5, 8])
print('Array is: ', a)
max = a.max()
min = a.min()

range = max - min
coeff = (max - min)/(max + min)

print('Range: ', range)
print('Coefficient of Range: ', coeff)

Array is:  [10 20 30  5  8]
Range:  25
Coefficient of Range:  0.7142857142857143
